baseURL = "https://www.mmomm.org/"
title   = "MingleMangleOfMyMind"

defaultContentLanguage        = "de"
defaultContentLanguageInSubdir = false

enableRobotsTXT = true
enableEmoji     = true
[pagination]
  pagerSize = 10

[build]
  writeStats = true

[outputs]
  home    = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page    = ["HTML"]

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "github"
