author = "Marcus Breiden"

[social]
  github   = "https://github.com/MMoMM-org"
  linkedin = "https://www.linkedin.com/in/marcusbreiden/"
  xing     = "https://www.xing.com/profile/Marcus_Breiden"
  youtube  = "https://www.youtube.com/@mmomm-org"
